world_address = "0x0203ccb9dcc21b5a1ec62aafde4180345291747333d819f14649f35d302315ad"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[indexing]
pending = true
contracts = [
  "erc721:0x0142712722e62a38f9c40fcc904610e1a14c70125876ecaaf25d803556734467" # Denshokan
]

[sql]
historical = [
  "hexed-Moves", 
  "hexed-DirectionsAvailable", 
  "hexed-Position", 
  "hexed-PositionCount",
  "hexed-Moved", 
  "hexed-Spawned", 
]
