world_address = "0x06cfabd4e07b5c3041fc0038cd8fe262a2c84d2992bd8f33d02fa9411c348331"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[indexing]
pending = true
contracts = [
  "erc721:0x0142712722e62a38f9c40fcc904610e1a14c70125876ecaaf25d803556734467" # Denshokan
]

[sql]
historical = [
  "hexed-Moves", 
  "hexed-DirectionsAvailable", 
  "hexed-Position", 
  "hexed-PositionCount",
  "hexed-Moved", 
  "hexed-Spawned", 
]
