world_address = "0x03f04a3a4f204c0f808df2e7ba0504fbf8be9bc575cff1289cc88aba6e29c8ae"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[indexing]
pending = true
contracts = [
  "erc721:0x0142712722e62a38f9c40fcc904610e1a14c70125876ecaaf25d803556734467" # Denshokan
]

[sql]
historical = [
  "hexed-Moves", 
  "hexed-DirectionsAvailable", 
  "hexed-Position", 
  "hexed-PositionCount",
  "hexed-Moved", 
  "hexed-Spawned", 
]
